command-aliases:
  glider:
    - g
    - topg
    - gay
  gsend:
    - gs
    - send
  gstatus:
    - status

# TODO: IMPLEMENT DEFAULT CLUSTER

default-cluster:
  # If you use plugins like LibreLogin, you need to set this to false
  enabled: true
  # Default cluster name that player should be sent when they join the server
  default: example

limbo-mechanic:
  enabled: true
  limbo-cluster: limbo
  target-cluster: lobby





# TODO: IMPLEMENT DEBUG LOGS

logging:
  debug-level: 0

bstats: true
# -------------------- DO NOT TOUCH -------------------- #
config-version: 1