command-aliases:
  - g
  - topg
  - gay

# TODO: IMPLEMENT DEFAULT CLUSTER

default-cluster:
  # If you use plugins like LibreLogin, you need to set this to false
  enabled: true
  default: example

limbo-mechanic:
  enabled: true
  cluster: limbo
  autosend: lobby








bstats: true
# -------------------- DO NOT TOUCH -------------------- #
config-version: 1