
database:
  ip: 127.0.0.1
  port: 3306
  username: "username"
  password: "yourpassword"
  databaseName: "database"
  maxPoolSize: 1500

command-aliases:
  - g
  - topg
  - gay

# TODO: IMPLEMENT DEFAULT CLUSTER

default-cluster:
  # If you use plugins like LibreLogin, you need to set this to false
  enabled: true
  default: example

limbo-mechanic:
  enabled: true
  cluster: limbo
  autosend: lobby









# -------------------- DO NOT TOUCH -------------------- #
config-version: 1